#ifndef DEF_IDX_HPP
#define DEF_IDX_HPP

namespace sdk {
	enum class def_idx : i16
	{
		NONE                        = 0,
		DEAGLE                      = 1,
		ELITE                       = 2,
		FIVESEVEN                   = 3,
		GLOCK                       = 4,
		AK47                        = 7,
		AUG                         = 8,
		AWP                         = 9,
		FAMAS                       = 10,
		G3SG1                       = 11,
		GALILAR                     = 13,
		M249                        = 14,
		M4A1                        = 16,
		MAC10                       = 17,
		P90                         = 19,
		ZONE_REPULSOR               = 20,
		MP5SD                       = 23,
		UMP45                       = 24,
		XM1014                      = 25,
		BIZON                       = 26,
		MAG7                        = 27,
		NEGEV                       = 28,
		SAWEDOFF                    = 29,
		TEC9                        = 30,
		TASER                       = 31,
		HKP2000                     = 32,
		MP7                         = 33,
		MP9                         = 34,
		NOVA                        = 35,
		P250                        = 36,
		SHIELD                      = 37,
		SCAR20                      = 38,
		SG556                       = 39,
		SSG08                       = 40,
		KNIFE_GG                    = 41,
		KNIFE_CT                    = 42,
		FLASHBANG                   = 43,
		HEGRENADE                   = 44,
		SMOKEGRENADE                = 45,
		MOLOTOV                     = 46,
		DECOY                       = 47,
		INCGRENADE                  = 48,
		C4                          = 49,
		HEALTHSHOT                  = 57,
		KNIFE_T                     = 59,
		M4A1_SILENCER               = 60,
		USP_SILENCER                = 61,
		CZ75A                       = 63,
		REVOLVER                    = 64,
		TAGRENADE                   = 68,
		FISTS                       = 69,
		BREACHCHARGE                = 70,
		TABLET                      = 72,
		MELEE                       = 74,
		AXE                         = 75,
		HAMMER                      = 76,
		SPANNER                     = 78,
		KNIFE_GHOST                 = 80,
		FIREBOMB                    = 81,
		DIVERSION                   = 82,
		FRAG_GRENADE                = 83,
		SNOWBALL                    = 84,
		BUMPMINE                    = 85,
		KNIFE_BAYONET               = 500,
		KNIFE_CSS                   = 503,
		KNIFE_FLIP                  = 505,
		KNIFE_GUT                   = 506,
		KNIFE_KARAMBIT              = 507,
		KNIFE_M9_BAYONET            = 508,
		KNIFE_TACTICAL              = 509,
		KNIFE_FALCHION              = 512,
		KNIFE_SURVIVAL_BOWIE        = 514,
		KNIFE_BUTTERFLY             = 515,
		KNIFE_PUSH                  = 516,
		KNIFE_CORD                  = 517,
		KNIFE_CANIS                 = 518,
		KNIFE_URSUS                 = 519,
		KNIFE_GYPSY_JACKKNIFE       = 520,
		KNIFE_OUTDOOR               = 521,
		KNIFE_STILETTO              = 522,
		KNIFE_WIDOWMAKER            = 523,
		KNIFE_SKELETON              = 525,
		GLOVE_STUDDED_BLOODHOUND    = 5027,
		GLOVE_T                     = 5028,
		GLOVE_CT                    = 5029,
		GLOVE_SPORTY                = 5030,
		GLOVE_SLICK                 = 5031,
		GLOVE_LEATHER_HANDWRAPS     = 5032,
		GLOVE_MOTORCYCLE            = 5033,
		GLOVE_SPECIALIST            = 5034,
		GLOVE_HYDRA                 = 5035,
		AGENT_BLUEBERRIES_BUCKSHOT  = 4619,
		AGENT_TWO_TIMES_MCCOY_TACP  = 4680,
		AGENT_COMMANDOR_MAE_JAMISON = 4711,
		AGENT_1ST_LIEUTENANT_FARLOW,
		AGENT_JOHN_KASK,
		AGENT_BIO_HAZ_SPECIALIST,
		AGENT_SERGEANT_BOMBSON,
		AGENT_CHEM_HAZ_SPECIALIST,
		AGENT_REZAN_THE_REDSHIRT      = 4718,
		AGENT_SIR_BLOODY_MIAMI_DARRYL = 4726,
		AGENT_SAFECRACKER_VOLTZMANN,
		AGENT_LITTLE_KEV,
		AGENT_GETAWAY_SALLY            = 4730,
		AGENT_NUMBER_K                 = 4732,
		AGENT_SIR_BLOODY_SILENT_DARRYL = 4733,
		AGENT_SIR_BLOODY_SKULLHEAD_DARRYL,
		AGENT_SIR_BLOODY_DARRYL_ROYALE,
		AGENT_SIR_BLOODY_LOUDMOUTH_DARRYL,
		AGENT_T            = 5036,
		AGENT_CT           = 5037,
		AGENT_GROUND_REBEL = 5105,
		AGENT_OSIRIS,
		AGENT_SHAHMAT,
		AGENT_MUHLIK,
		AGENT_SOLDIER = 5205,
		AGENT_ENFORCER,
		AGENT_SLINGSHOT,
		AGENT_STREET_SOLDIER,
		AGENT_OPERATOR = 5305,
		AGENT_MARKUS_DELROW,
		AGENT_MICHAEL_SYFERS,
		AGENT_AVA,
		AGENT_3RD_COMMANDO_COMPANY = 5400,
		AGENT_SEAL_TEAM_6_SOLDIER,
		AGENT_BUCKSHOT,
		AGENT_TWO_TIMES_MCCOY_USAF,
		AGENT_RICKSAW,
		AGENT_DRAGOMIR = 5500,
		AGENT_MAXIMUS,
		AGENT_REZAN_THE_READY,
		AGENT_BLACKWOLF = 5503,
		AGENT_THE_DOCTOR,
		AGENT_DRAGOMIR_FOOTSOLDIERS,
		AGENT_B_SQUADRON_OFFICER = 5601
	};
} // namespace sdk

#endif // DEF_IDX_HPP